# Generated by Django 5.2.17 on 2026-10-05 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
        ('ExpeditionApp', '0001_initial'),
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.PositiveBigIntegerField()),
                ('statut', models.CharField(choices=[('p', 'propose'), ('a', 'accepte'), ('r', 'refuse'), ('re', 'retiree')], default='p', max_length=100)),
                ('date_proposition', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntrepriseApp.entreprise')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionApp.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculeApp.vehicule')),
            ],
        ),
    ]
