# Generated by Django 5.2.17 on 2026-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
