# Generated by Django 5.2.17 on 2026-10-06 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "l'adresse ne peut avoir moins de 20 char "), django.core.validators.MaxLengthValidator(400, "l'adresse ne peut pas depasser les 400 char")]),
        ),
    ]
