# Generated by Django 5.2.17 on 2026-10-06 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La capacité doit être strictement supérieure à 0.')]),
        ),
    ]
